In [1]:
"learning R"

[1] "learning R"

In [2]:
5+5

[1] 10

In [4]:
#for loops
for(i in -3:3){
    print(i)
}

[1] -3
[1] -2
[1] -1
[1] 0
[1] 1
[1] 2
[1] 3


In [8]:
#assigning
name<-'manya hegde'
age<-20
name
age

[1] "manya hegde"

[1] 20

In [9]:
#concatination
text<-'R programming'
paste('Learning',text)

[1] "Learning R programming"

In [14]:
#numeric
x<-10.5

#integer
y<-10L

#complex
z<-8i+3

#character/string
m='hello'

#boolean/logical
b=TRUE

In [15]:
#to check the data type of a variable
class(x)
class(y)
class(z)
class(m)
class(b)

[1] "numeric"

[1] "integer"

[1] "complex"

[1] "character"

[1] "logical"

In [16]:
#type conversion
x2=as.integer(x)
x2

[1] 10

In [19]:
y2=as.complex(y)
y2

[1] 10+0i

In [20]:
z2=as.numeric(z)
z2

Warning message in eval(expr, envir, enclos):
"imaginary parts discarded in coercion"

[1] 3

In [21]:
#max and min functions
max(10, 5, 13, 2)
min(9,0,1)

[1] 13

[1] 0

In [22]:
#square root
sqrt(1000)

[1] 31.62278

In [23]:
#ceiling and floor functions

ceiling(1.4)

floor(1.4)

[1] 2

[1] 1

In [27]:
#cat() function

str='R programming
for Data Science!'

str

cat(str)

[1] "R programming\nfor Data Science!"

R programming
for Data Science!

In [28]:
#string length

text="hello world!"
nchar(text)

[1] 12

In [29]:
#to check if a character or a sequence of characters are present in a string

str="Python for Machine Learning"
grepl("for",str)

grepl('hello',str)

[1] TRUE

[1] FALSE

In [30]:
#escape character-To insert characters that are illegal in a string

str="Running programs on \"RStudio\" with Anaconda is a straightforward process"
str
cat(str)

[1] "Running programs on \"RStudio\" with Anaconda is a straightforward process"

Running programs on "RStudio" with Anaconda is a straightforward process

In [31]:
#if else
a <- 200
b <- 33

if (b > a) {
  print ("b is greater than a")
} else {
  print("b is not greater than a")
}

[1] "b is not greater than a"


In [35]:
my_var <- 3

my_var <<- 3 #global assigner

3 -> my_var #same as my_var<-3

3 ->> my_var

my_var 

[1] 3

In [37]:
#to create a series of numbers in a sequence
x<-1:10
x

[1]  1  2  3  4  5  6  7  8  9 10

In [40]:
#to find out if an element belongs to a vector
x=1:10
y=2:6
x%in%y

[1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE FALSE FALSE

In [41]:
#and operator
a <- 200
b <- 33
c <- 500

if (a > b & c > a) {
  print("Both conditions are true")
}

[1] "Both conditions are true"


In [42]:
#or operator
a <- 200
b <- 33
c <- 500

if (a > b | a > c) {
  print("At least one of the conditions is true")
}

[1] "At least one of the conditions is true"


In [44]:
#while and break
i <- 1
while (i < 6) {
  print(i)
  i <- i + 1
  if (i == 4) {
    break
  }
}

[1] 1
[1] 2
[1] 3


In [45]:
#next statement
i <- 0
while (i < 6) {
  i <- i + 1
  if (i == 3) {
    next #skips value 3
  }
  print(i)
}

[1] 1
[1] 2
[1] 4
[1] 5
[1] 6


In [48]:
#list
fruits <- list("apple", "banana", "cherry")
for (x in fruits) {
  print(x)
}

[1] "apple"
[1] "banana"
[1] "cherry"


In [49]:
#functions
my_function <- function() {
  print("Hello World!")
}

my_function() # call the function named my_function

[1] "Hello World!"


In [51]:
name<-function(fname){
    paste(fname,'hegde')
}
name('manya')

[1] "manya hegde"

In [53]:
multiply<-function(x,y){
    return (x*y)
}
multiply(5,2)

[1] 10

In [54]:
#nested function
Nested_function <- function(x, y) {
  a <- x + y
  return(a)
}

Nested_function(Nested_function(2,2), Nested_function(3,3))

[1] 10

In [55]:
txt <- "awesome"
my_function <- function() {
  paste("R is", txt)
}

my_function()

[1] "R is awesome"

In [10]:
#vectors-list of items of same type

#a list
random<-list('a',4,'o','i',1)

#a vector
fruits<-c('apple','chikku',0, 8)#will convert 0 & 8 to string
numbers <- 1:10

random
fruits
numbers
length(numbers)

[[1]]
[1] "a"

[[2]]
[1] 4

[[3]]
[1] "o"

[[4]]
[1] "i"

[[5]]
[1] 1

[1] "apple"  "chikku" "0"      "8"

[1]  1  2  3  4  5  6  7  8  9 10

[1] 10

In [18]:
#sorting a vector
vector<-c('rahul','sanjay','priya','alia')
vector
sort(vector)

#to access the first element of vector
vector[1]

#to access the first and third item (banana and orange)
vector[c(1, 3)]

#to access all items except for the first item
vector[c(-1)]

[1] "rahul"  "sanjay" "priya"  "alia"

[1] "alia"   "priya"  "rahul"  "sanjay"

[1] "rahul"

[1] "rahul" "priya"

[1] "sanjay" "priya"  "alia"

In [19]:
vector[c(-1,-2)]

[1] "priya" "alia"

In [21]:
#to change an item in the vector
vector[2]<-'dev'
vector

[1] "rahul" "dev"   "priya" "alia"

In [24]:
#repeat vector

repeat_each <- rep(c(1,2,3), each = 3)
repeat_each

repeat_times <- rep(c(1,2,3), times = 3)
repeat_times

repeat_indepent <- rep(c(1,2,3), times = c(5,2,1))
repeat_indepent

[1] 1 1 1 2 2 2 3 3 3

[1] 1 2 3 1 2 3 1 2 3

[1] 1 1 1 1 1 2 2 3

In [25]:
#generating sequenced vectors
numbers<-seq(from = 0, to = 100, by = 20)
numbers

[1]   0  20  40  60  80 100

In [28]:
#add item to the list
thislist <- list("apple", "banana", "cherry")
append(thislist, "orange",after = 1)

[[1]]
[1] "apple"

[[2]]
[1] "orange"

[[3]]
[1] "banana"

[[4]]
[1] "cherry"

In [32]:
#remove an item
thislist <- list("apple", "banana", "cherry")
thislist<- thislist[-1]
thislist

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

In [33]:
#range of indexes
thislist <- list("apple", "banana", "cherry")
thislist[2:3]

[[1]]
[1] "banana"

[[2]]
[1] "cherry"

In [34]:
#join 2 lists
list1 <- list("a", "b", "c")
list2 <- list(1,2,3)
list3 <- c(list1,list2)
list3

[[1]]
[1] "a"

[[2]]
[1] "b"

[[3]]
[1] "c"

[[4]]
[1] 1

[[5]]
[1] 2

[[6]]
[1] 3

In [67]:
# Create a matrix
thismatrix <- matrix(c(1,2,3,4,5,6), nrow = 2, ncol = 3)
thismatrix

[,1] [,2] [,3]
[1,] 1    3    5   
[2,] 2    4    6

In [68]:
thismatrix[1,2]

[1] 3

In [69]:
thismatrix[,c(1,2)] #all rows,1st and 2nd columns

[,1] [,2]
[1,] 1    3   
[2,] 2    4

In [70]:
#to add additional column
thismatrix<-cbind(thismatrix,c(7,8))
thismatrix

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8

In [71]:
#to add additional row
thismatrix<-rbind(thismatrix,c(3,2,1,5))
thismatrix

[,1] [,2] [,3] [,4]
[1,] 1    3    5    7   
[2,] 2    4    6    8   
[3,] 3    2    1    5

In [72]:
#Remove the first row and the first column
thismatrix <- thismatrix[-c(1), -c(1)]
thismatrix

[,1] [,2] [,3]
[1,] 4    6    8   
[2,] 2    1    5

In [74]:
#to check if an item is present int the matrix
8 %in% thismatrix

[1] TRUE

In [75]:
#dimension
dim(thismatrix)

[1] 2 3

In [76]:
#length
length(thismatrix)

[1] 6

In [77]:
#loop through a matrix
thismatrix <- matrix(c("apple", "banana", "cherry", "orange"), nrow = 2, ncol = 2)

for (rows in 1:nrow(thismatrix)) {
  for (columns in 1:ncol(thismatrix)) {
    print(thismatrix[rows, columns])
  }
}

[1] "apple"
[1] "cherry"
[1] "banana"
[1] "orange"


In [79]:
# An array with one dimension with values ranging from 1 to 24
thisarray <- c(1:24)
thisarray

[1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24

In [81]:
# Create a data frame
Data_Frame <- data.frame (
  Training = c("Strength", "Stamina", "Other"),
  Pulse = c(100, 150, 120),
  Duration = c(60, 30, 45)
)

# Print the data frame
Data_Frame

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45

In [82]:
summary(Data_Frame)

     Training     Pulse          Duration   
 Other   :1   Min.   :100.0   Min.   :30.0  
 Stamina :1   1st Qu.:110.0   1st Qu.:37.5  
 Strength:1   Median :120.0   Median :45.0  
              Mean   :123.3   Mean   :45.0  
              3rd Qu.:135.0   3rd Qu.:52.5  
              Max.   :150.0   Max.   :60.0  

In [84]:
Data_Frame[1]

Training
1 Strength
2 Stamina 
3 Other

In [85]:
Data_Frame[["Training"]]

[1] Strength Stamina  Other   
Levels: Other Stamina Strength

In [86]:
Data_Frame$Training

[1] Strength Stamina  Other   
Levels: Other Stamina Strength

In [89]:
# Add a new row
New_row_DF <- rbind(Data_Frame, c("Strength", 110, 110))
New_row_DF

Training Pulse Duration
1 Strength 100   60      
2 Stamina  150   30      
3 Other    120   45      
4 Strength 110   110

In [90]:
# Add a new column
New_col_DF <- cbind(Data_Frame, Steps = c(1000, 6000, 2000))
New_col_DF

Training Pulse Duration Steps
1 Strength 100   60       1000 
2 Stamina  150   30       6000 
3 Other    120   45       2000

In [91]:
# Remove the first row and column
Data_Frame_New <- Data_Frame[-c(1), -c(1)]

In [92]:
Data_Frame_New

Pulse Duration
2 150   30      
3 120   45

In [93]:
dim(Data_Frame_New)

[1] 2 2

In [94]:
ncol(Data_Frame)

[1] 3

In [95]:
nrow(Data_Frame)

[1] 3

In [97]:
length(Data_Frame) #this also returns number of columns

[1] 3

In [98]:
#factor - used to categorize data

# Create a factor
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"))

# Print the factor
music_genre

[1] Jazz    Rock    Classic Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock

In [99]:
#to print the levels
levels(music_genre)

[1] "Classic" "Jazz"    "Pop"     "Rock"

In [100]:
#we can also set the levels
music_genre <- factor(c("Jazz", "Rock", "Classic", "Classic", "Pop", "Jazz", "Rock", "Jazz"), levels = c("Classic", "Jazz", "Pop", "Rock", "Other"))

levels(music_genre)

[1] "Classic" "Jazz"    "Pop"     "Rock"    "Other"

In [101]:
length(music_genre)

[1] 8

In [102]:
music_genre[3]

[1] Classic
Levels: Classic Jazz Pop Rock Other

In [104]:
music_genre[3] <- "Pop"
music_genre

[1] Jazz    Rock    Pop     Classic Pop     Jazz    Rock    Jazz   
Levels: Classic Jazz Pop Rock Other